### ISSUE TITLE
Guide level explanation and progress tracker

### ISSUE THREAD

**Issue by Sriram-7451** [Sriram-7451/ZeldaFeatExension#11]
The player needs to understand the guide level that is being purchased by them. There also needs to be a screen that explains each guide level and credit equivalency for that. There also needs to be a design for the progress tracker which keeps tab of korok seeds obtained and the guide level left over hints for the location of korok seeds.

- [ ] Design a screen for Guide level explanation
- [ ] Progress tracker design for display and database 
- [ ] Korok seeds location input in database
- [ ] Guide level leftover hint tracker
- [ ] Test all the features and gameplay
